### ISSUE TITLE
初始化遇到了问题..

### ISSUE THREAD

**Issue by Yyur1nnnn** [djkcyl/ABot-Graia#13]
Traceback (most recent call last):
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\qq\ABotGraia\ABot-Graia\main.py", line 86, in <module>
    app.launch_blocking()
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\graia\application\__init__.py", line 1613, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "C:\Users\Izumi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\graia\application\__init__.py", line 1503, in initialize
    await self.authenticate()
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\graia\application\utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\graia\application\__init__.py", line 301, in authenticate
    async with self.session.post(
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Izumi\AppData\Local\pypoetry\Cache\virtualenvs\abot-MlpB7-1x-py3.9\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [远程计算机拒绝网络连 接。]

**Comment by djkcyl** [comment]
你的mah有成功运行吗
