### ISSUE TITLE
虚拟环境 没启动起来

### ISSUE THREAD

**Issue by cdlaimin** [djkcyl/ABot-Graia#17]
2021-11-26 09:11:00.436 | INFO     | config:save_config:81 - 正在保存配置文件
2021-11-26 09:11:00.453 | DEBUG    | graia.saya:require:111 - require saya.ChatMS
2021-11-26 09:11:00.455 | INFO     | graia.saya:require:134 - module loading finished: saya.ChatMS
2021-11-26 09:11:00.455 | DEBUG    | graia.saya:require:111 - require saya.Lottery
2021-11-26 09:11:01.257 | ERROR    | graia.ariadne.util:loguru_excepthook:73 - Exception:
Traceback (most recent call last):

> File "/root/qqbot/ABot-Graia/main.py", line 49, in <module>
    saya.require(f"saya.{module.split('.')[0]}")
    │    └ <function Saya.require at 0x7f71b43d7ca0>
    └ <graia.saya.Saya object at 0x7f71ae9a32e0>

  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/graia/saya/__init__.py", line 120, in require
    channel = self.require_resolve(module)
              │    │               └ 'saya.Lottery'
              │    └ <function Saya.require_resolve at 0x7f71b43d7b80>
              └ <graia.saya.Saya object at 0x7f71ae9a32e0>
  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/graia/saya/__init__.py", line 76, in require_resolve
    imported_module = importlib.import_module(module, module)
                      │         │             │       └ 'saya.Lottery'
                      │         │             └ 'saya.Lottery'
                      │         └ <function import_module at 0x7f71b4782f70>
                      └ <module 'importlib' from '/usr/lib64/python3.9/importlib/__init__.py'>
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ 'saya.Lottery'
           │          │           │    └ 0
           │          │           └ 'saya.Lottery'
           │          └ <function _gcd_import at 0x7f71b6584310>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/root/qqbot/ABot-Graia/saya/Lottery/__init__.py", line 28, in <module>
    from .lottery_image import qrgen, qrdecode

  File "/root/qqbot/ABot-Graia/saya/Lottery/lottery_image.py", line 6, in <module>
    from pyzbar import pyzbar

  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/pyzbar/wrapper.py", line 139, in <module>
    zbar_version = zbar_function(
                   └ <function zbar_function at 0x7f71a82cd040>
  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/pyzbar/wrapper.py", line 136, in zbar_function
    return prototype((fname, load_libzbar()))
           │          │      └ <function load_libzbar at 0x7f71a82c1820>
           │          └ 'zbar_version'
           └ <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/pyzbar/wrapper.py", line 115, in load_libzbar
    libzbar, dependencies = zbar_library.load()
                            │            └ <function load at 0x7f71a82c1ee0>
                            └ <module 'pyzbar.zbar_library' from '/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/...
  File "/root/qqbot/ABot-Graia/virtualenvs/abot-mahv2-i9ZxcU2y-py3.9/lib/python3.9/site-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')

ImportError: Unable to find zbar shared library

**Comment by djkcyl** [comment]
**缺少 zbar 库**


CentOS 执行 
```shell
yum install python-devel
yum install zbar-devel
```
Ubuntu 执行
```shell
sudo apt install libzbar-dev
```

**Comment by cdlaimin** [comment]
chatms 的词典地址被加了cdn 好像还跳转了一次 后面的解析出错了

**Comment by djkcyl** [comment]
> chatms 的词典地址被加了cdn 好像还跳转了一次 后面的解析出错了

这个是网络问题，无解，你可以手动创建data.json然后把那个地址的内容复制进去
