### ISSUE TITLE
启动main.py的时候报错No module named '_speech_py_impl'

### ISSUE THREAD

**Issue by Bestlm** [djkcyl/ABot-Graia#19]
2021-12-09 22:11:11.908 | DEBUG    | graia.saya:require:111 - require saya.AzureTTS
2021-12-09 22:11:11.945 | ERROR    | graia.ariadne.util:loguru_excepthook:87 - Exception:
Traceback (most recent call last):

  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
           │         │             └ 'azure.cognitiveservices.speech._speech_py_impl'
           │         └ <function import_module at 0x7f62490c3310>
           └ <module 'importlib' from '/usr/local/sbin/python-3.9/lib/python3.9/importlib/__init__.py'>
  File "/usr/local/sbin/python-3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'azure.cognitiveservices.speech._speech_py_impl'
           │          └ <function _gcd_import at 0x7f6250668310>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/sbin/python-3.9/lib/python3.9/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "/usr/local/ABot/ABot-Graia/main.py", line 60, in <module>
    saya.require(f"saya.{module.split('.')[0]}")
    │    └ <function Saya.require at 0x7f6243fb1310>
    └ <graia.saya.Saya object at 0x7f6241457eb0>

  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/graia/saya/__init__.py", line 120, in require
    channel = self.require_resolve(module)
              │    │               └ 'saya.AzureTTS'
              │    └ <function Saya.require_resolve at 0x7f6243fb11f0>
              └ <graia.saya.Saya object at 0x7f6241457eb0>
  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/graia/saya/__init__.py", line 76, in require_resolve
    imported_module = importlib.import_module(module, module)
                      │         │             │       └ 'saya.AzureTTS'
                      │         │             └ 'saya.AzureTTS'
                      │         └ <function import_module at 0x7f62490c3310>
                      └ <module 'importlib' from '/usr/local/sbin/python-3.9/lib/python3.9/importlib/__init__.py'>
  File "/usr/local/sbin/python-3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ 'saya.AzureTTS'
           │          │           │    └ 0
           │          │           └ 'saya.AzureTTS'
           │          └ <function _gcd_import at 0x7f6250668310>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/usr/local/ABot/ABot-Graia/saya/AzureTTS/__init__.py", line 16, in <module>
    from azure.cognitiveservices.speech import (

  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
    from .speech import *
  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/azure/cognitiveservices/speech/speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 17, in <module>
    _speech_py_impl = swig_import_helper()
                      └ <function swig_import_helper at 0x7f622211c160>
  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 16, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
           │         └ <function import_module at 0x7f62490c3310>
           └ <module 'importlib' from '/usr/local/sbin/python-3.9/lib/python3.9/importlib/__init__.py'>
  File "/usr/local/sbin/python-3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ '_speech_py_impl'
           │          └ <function _gcd_import at 0x7f6250668310>
           └ <module 'importlib._bootstrap' (frozen)>

ModuleNotFoundError: No module named '_speech_py_impl'

尝试过https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/747，但未解决

**Comment by Bestlm** [comment]
已解决

**Comment by djkcyl** [comment]
可以试着把大致的解决步骤发出来，以便他人需要时查阅

**Comment by szukyy** [comment]
请问如何解决的呀
