### ISSUE TITLE
机器人可以正确启动，但是发送帮助信息等消息会报错

### ISSUE THREAD

**Issue by Bestlm** [djkcyl/ABot-Graia#20]
![image](https://user-images.githubusercontent.com/29437027/145501791-05b7140b-a5e4-403b-bacd-6a2fd6ce9771.png)
```2021-12-10 09:27:23.010 | INFO     | graia.ariadne.model:log_group_message:96 - 197998492: [BOT测试群(960041285)] Bestlm(303474214) -> '功能 14'
2021-12-10 09:27:23.012 | ERROR    | graia.ariadne.util:loguru_excepthook:87 - Exception:
Traceback (most recent call last):

  File "/usr/local/ABot/ABot-Graia/main.py", line 65, in <module>
    app.launch_blocking()
    │   └ <function Ariadne.launch_blocking at 0x7fb51f5a2790>
    └ <graia.ariadne.app.Ariadne object at 0x7fb51f541790>

  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/graia/ariadne/app.py", line 1332, in launch_blocking
    self.loop.run_until_complete(self.lifecycle())
    │    │    │                  │    └ <function Ariadne.lifecycle at 0x7fb51f5a2700>
    │    │    │                  └ <graia.ariadne.app.Ariadne object at 0x7fb51f541790>
    │    │    └ <function BaseEventLoop.run_until_complete at 0x7fb5236808b0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <graia.ariadne.app.Ariadne object at 0x7fb51f541790>
  File "/usr/local/sbin/python-3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fb523680820>
    app.launch_blocking()
    │   └ <function Ariadne.launch_blocking at 0x7fb51f5a2790>
    └ <graia.ariadne.app.Ariadne object at 0x7fb51f541790>

  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/graia/ariadne/app.py", line 1332, in launch_blocking
    self.loop.run_until_complete(self.lifecycle())
    │    │    │                  │    └ <function Ariadne.lifecycle at 0x7fb51f5a2700>
    │    │    │                  └ <graia.ariadne.app.Ariadne object at 0x7fb51f541790>
    │    │    └ <function BaseEventLoop.run_until_complete at 0x7fb5236808b0>
 │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  <graia.ariadne.app.Ariadne object at 0x7fb51f541790>
  File "/usr/local/sbin/python-3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fb523680820>
  └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/sbin/python-3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fb5236833a0>
  └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/sbin/python-3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fb523ab59d0>
  └ <Handle <TaskStepMethWrapper object at 0x7fb4ed830070>()>
  File "/usr/local/sbin/python-3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
│    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fb4ed830070>()>
│    │            │    └ <member '_callback' of 'Handle' objects>
│    │            └ <Handle <TaskStepMethWrapper object at 0x7fb4ed830070>()>
│    └ <member '_context' of 'Handle' objects>
└ <Handle <TaskStepMethWrapper object at 0x7fb4ed830070>()>
> File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 151, in Executor
    parameter_compile_result[name] = await dii.lookup_param(name, annotation, default, optimized_log)
    │                        │             │   │            │     │           │        └ []
│                        │             │   │            │     │           └ None
                         │             │   │            │     └ <class 'graia.ariadne.message.parser.pattern.WildcardMatch'>
    │                        │             │   │            └ 'func'
                         │             │   └ <function DispatcherInterface.lookup_param at 0x7fb526db88b0>
    │                        │             └ <graia.broadcast.interfaces.dispatcher.DispatcherInterface object at 0x7fb51f53a6a0>
    │                        └ 'func'
  └ {'group': Group(id=960041285, name='BOT测试群', accountPerm=<MemberPerm.Administrator: 'ADMINISTRATOR'>)}
  File "/usr/local/sbin/python-3.9/lib/python3.9/site-packages/graia/broadcast/interfaces/dispatcher.py", line 108, in lookup_param
    raise RequirementCrashed(
          └ <class 'graia.broadcast.exceptions.RequirementCrashed'>

graia.broadcast.exceptions.RequirementCrashed: ('the dispatching requirement crashed: ', 'func', <class 'graia.ariadne.message.parser.pattern.WildcardMatch'>, None)
```

**Comment by Bestlm** [comment]
> **依赖版本问题**
> 
> 如果您是用的是 poetry，执行该命令降级`graia-ariadne-dev` 至 `2021.12.6.3` 版本即可。
> 
> ```shell
> poetry add graia-ariadne-dev@2021.12.6.3
> ```
> 
> 如果您使用的是pip等其他依赖管理器，自行查询降级方案。

感谢回复，已解决，但是某些功能还会引发捕获异常
![000000000-000000000-874678FC234EF4DF8064F843BF9B8910](https://user-images.githubusercontent.com/29437027/145505013-899a99d5-2589-4147-b118-2e9fe639e3ce.jpg)

**Comment by djkcyl** [comment]
> > **依赖版本问题**
> > 
> > 如果您是用的是 poetry，执行该命令降级`graia-ariadne-dev` 至 `2021.12.6.3` 版本即可。
> > 
> > ```shell
> > poetry add graia-ariadne-dev@2021.12.6.3
> > ```
> > 
> > 如果您使用的是pip等其他依赖管理器，自行查询降级方案。
> 
> 感谢回复，已解决，但是某些功能还会引发捕获异常
> ![000000000-000000000-874678FC234EF4DF8064F843BF9B8910](https://user-images.githubusercontent.com/29437027/145505013-899a99d5-2589-4147-b118-2e9fe639e3ce.jpg)
> 
> 

这个玩意啊，我都没测试过，不敢开，但逻辑是得有一期已经开奖了的才能

**Comment by djkcyl** [comment]
新版本发了，已修复
